apiVersion: apps/v1
kind: Deployment
metadata:
  name: sever-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sever-deployment
  template:
    metadata:
      labels:
        app: sever-deployment
    spec:
      containers:
      - name: web-server
        image: shawkani/multi-web-server
        env:
          - name: REDIS_HOST
            value: redis-cluster-ip-service
          - name: REDIS_PORT
            value: "6379"
          - name: PGHOST
            value: postgres-cluster-ip-service
          - name: PGPORT
            value: "5432"
          - name: PGUSER
            value: postgres
          - name: PGDATABASE
            value: postgres
          - name: PGPASSWORD
            valueFrom:
                secretKeyRef:
                  key: PGPASSWORD
                  name: pgpassword
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
